version: "3.8"

services: 
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes: 
      - ../TodoList:/data/db
  api:
    image: rest_api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5000:80
    environment:
      DB_URL: mongodb://mongo:27017/TodoList

    # depends_on:
    #   - db
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27018:27017"
  #   volumes: 
  #     - ../TodoList:/data/db

# volumes: 
#   TodoList:

# services:
#   mongo:
#     image: MongoDB
#     build: 
#       context: ./mongoDb
#       dockerfile: Dockerfile
#     volumes:
#       - "./mongoDb/mongoVolume/db:/data/db"
#     restart: always
#     ports:
#       - "27018:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: 
#       MONGO_INITDB_ROOT_PASSWORD: 